services:
  - type: web
    name: tty-live
    env: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: SUPABASE_URL
        value: https://ghpmcjozeubrmiuzyfey.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdocG1jam96ZXVicm1pdXp5ZmV5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzkyNjMyNiwiZXhwIjoyMDkzNTAyMzI2fQ.UqXXSemIA3-mxlar32e84TKUlYxh9lhbSk5oVvxfrn0
      - key: STRIPE_SECRET_KEY
        value: sk_test_51SsYnBCMxCYkRCoNMjs5Z1nBK0niCtmtJBQTtR7Ml1uo8sWsJN1Ujr7U3WOew6L2wVCSLftWkdiVjPGzGxJpIpmh00L7rsJb1B
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_LfmkvHGU8Nsm4UTIhtZXvmN6PtmYAYjk
      - key: STRIPE_BASIC_PRICE_ID
        value: price_1TTYqGCBOoQTb0Npwes7Qbia
      - key: STRIPE_PRO_PRICE_ID
        value: price_1TTYqLCBOoQTb0NpsP3FnfNP
      - key: DEEPSEEK_API_KEY
        value: sk-783270eb5a8643888c1bb1565708554f
      - key: FRONTEND_URL
        value: https://tty-live.vercel.app
      - key: SERVER_URL
        value: https://tty-live.onrender.com
      - key: VIEWER_URL
        value: https://tty-live-viewer.vercel.app
      - key: GITHUB_CLIENT_ID
        value: REPLACE_AFTER_CREATING_OAUTH_APP
      - key: GITHUB_CLIENT_SECRET
        value: REPLACE_AFTER_CREATING_OAUTH_APP
